all: graph graf.so

graf.o: main.c graf.h
	gcc -Wall -g -c main.c -lm

main.o: main.c graf.h
	gcc -Wall -g -c main.c

graf.so: graf.o
	gcc -shared -o main.o

graph: main.o graf.so
	gcc -Wall -g -o graph main.o ./graf.so -lm

.PHONY: clean

clean:
	rm -f *.o *.a *.so graph


